### ISSUE TITLE
Invalid link in readme

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanosbench#15]
There is an invalid link in Readme.  

For any adjustment, edit benchmarks/monitor/main.go or related template. make gen will generate the YAMLs.

The path  'benchmarks/monitor/main.go' doesn't exist.

**Comment by adhilcodes** [comment]
> There is an invalid link in Readme.
> 
> For any adjustment, edit benchmarks/monitor/main.go or related template. make gen will generate the YAMLs.
> 
> The path 'benchmarks/monitor/main.go' doesn't exist.

`https://github.com/thanos-io/thanosbench/blob/db8874ab23f480f33cdb4ac4eeec57562f566dd8/benchmarks/monitor/main.go#L25`
This is that link and that **blob** file ismissing
