### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by yxyx520** [thanos-io/thanosbench#27]
go: extracting github.com/fatih/structtag v1.1.0
go: extracting golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: extracting github.com/kr/text v0.1.0
go: extracting golang.org/x/text v0.3.2
all modules verified
(re)installing /root/.go//bin/promu-v0.5.0
flag provided but not defined: -modfile
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [/root/.go//bin/promu-v0.5.0] Error 2

**Comment by GiedriusS** [comment]
Please use 1.14 or higher.
