### ISSUE TITLE
go: github.com/bwplotka/bingo@v0.2.2: missing go.sum entry (Go 1.16.2, on Aarch64)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [thanos-io/thanosbench#35]
Hi.

Got such a bug:

> $ make
> (re)installing /home/oceanfish81/go/bin/bingo-v0.2.2
> go: github.com/bwplotka/bingo@v0.2.2: missing go.sum entry; to add it:
>         go mod download github.com/bwplotka/bingo
> make: *** [.bingo/Variables.mk:23: /home/oceanfish81/go/bin/bingo-v0.2.2] Error 1

Please take the following diff in to an account:

https://gist.github.com/advancedwebdeveloper/323e6f83ec3bb8635730a31d3c1d7f87

> $ go version
> go version
> go version go1.16.2 linux/arm64

> $ go env
> GO111MODULE=""
> GOARCH="arm64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="arm64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/usr/local/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
> GOVCS=""
> GOVERSION="go1.16.2"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/thanosbench/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build648664304=/tmp/go-build -gno-record-gcc-switches"

@ianlancetaylor ,
no success via

> $   go mod download github.com/bwplotka/bingo
> go mod download: module github.com/bwplotka/bingo: not a known dependency
. Even if i would restore the go.sum file

**Comment by yeya24** [comment]
Fixed by https://github.com/thanos-io/thanosbench/pull/40
